### ISSUE TITLE
Option to remove duplicates?

### ISSUE THREAD

**Issue by njanik** [roosta/i3wsr#12]
Hi,
In some workspace, I use the same app multiples times. For example: the terminal. I have 4 open terminals. Is there a way to display the name "terminal" only one time instead of 4 times ?

Thank you!

**Comment by roosta** [comment]
not at the moment no, no way to filter duplicates. I'll consider adding it as an option on the next release along with support for `wm_instance` which might also help with this issue.

**Comment by njanik** [comment]
Thank you!
