### ISSUE TITLE
Using alias name for icons

### ISSUE THREAD

**Issue by tosti007** [roosta/i3wsr#15]
Hey there, 
I want to start off by saying I really enjoy this project, thank you so much! 

This might be more of a feature request, but maybe you already looked at it. Anyhow, currently the icons section does not seem to use the alias section names. I think it would be nice to match a name with an alias and then use that alias in the icons section. 

The reason for this is it allows for easier definitions of icons, a simple example configuration in the current situation:
```
[icons]
"i-three-workspaces-renamer-v1.30" = "♡"

[aliases]
"i-three-workspaces-renamer-v1.30" = "i3wsr"
```

Which would be nice to simplify to:
 ```
[icons]
"i3wsr" = "♡"

[aliases]
"i-three-workspaces-renamer-v1.30" = "i3wsr"
```

**Comment by roosta** [comment]
Thank you for using i3wsr :)

These are good suggestions, I'll see about implementing them when I have the time. Don't hold your breath though, might take a little while. If you are up to it, a pull request would be greatly appreciated. This goes for #16 as well.
