### ISSUE TITLE
No-names tag does not work with default_icons

### ISSUE THREAD

**Issue by gschievelbein** [roosta/i3wsr#17]
When no-names is set to true, the names of applications that use the default_icon are still shown

**Comment by roosta** [comment]
Hi, thank you for reporting. There was a decision made in a [previous pull request](https://github.com/roosta/i3wsr/pull/14#discussion_r433949368), that it doesn't make that much sense to hide the name when default icon is enabled, how would you tell apart applications?

If this is a problem for you I'll patch it, but out of curiosity whats the use-case here?
EDIT: spelling

**Comment by gschievelbein** [comment]
Hi. The main issue is that some applications have really long names that take almost half of the bar. When multiple applications without custom icons are open, the polybar i3 module pushes other modules out of view.

I also think that it does not make much sense to hide the name of some applications but not of others. I use the icons so that a quick glance at the corner of my screen is enough to know what I have open in each workspace. That is not possible if some application display their titles.

I set up custom icons to common applications that are always open. The default icon would be enough to find out in which workspace the other applications are.

**Comment by roosta** [comment]
Thanks for the explanation, makes sense. I pushed [a fix](https://github.com/roosta/i3wsr/commit/23ace5c1e847dc73c29bf753683aae2f7569811c) under the `hotfix` branch, would you mind trying it out before I draft a new version?

**Comment by gschievelbein** [comment]
Thank you. It seems to be working fine with no issues so far.
