### ISSUE TITLE
Issue when trying to install i3wsr

### ISSUE THREAD

**Issue by ghost** [roosta/i3wsr#18]
I get this error when running 'cargo install i3wsr':
> error: linking with `cc` failed: exit code: 1
> |
>   = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.0.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.1.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.10.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.11.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.12.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.13.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.14.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.15.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.2.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.3.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.4.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.5.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.6.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.7.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.8.rcgu.o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.i3wsr.cf9699zw-cgu.9.rcgu.o" "-o" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2" "/tmp/cargo-installyqQgJ1/release/deps/i3wsr-d97f0d410688ada2.2w4h3me5ehghndzl.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/cargo-installyqQgJ1/release/deps" "-L" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-installyqQgJ1/release/deps/libclap-c526051765af2762.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libvec_map-aa70a9b8a46da868.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libtextwrap-fa17f008fcb6a641.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libunicode_width-788a7bb8f6848a2f.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libstrsim-0f90bfc1e86d296f.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libbitflags-ce22fd3ba40b4cc7.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libatty-7dec57944fd8b8e1.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libansi_term-87d88f946b658a4b.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libexitfailure-50dd0472c4a40bbc.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libi3wsr-625593a5eb90c448.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libtoml-f2b47329b1fc0843.rlib" "/tmp/cargo-installyqQgJ1/release/deps/liblazy_static-7838e4e1e8aa819d.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libfailure-5245e130a93a5f85.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libbacktrace-1461e14f88f553da.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libminiz_oxide-a8bf6954a40d2e67.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libadler-3d2dfd5868192abb.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libobject-9be1ef9b7785053d.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libaddr2line-e2f1bfbbe48e656e.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libgimli-4fabdeae3b437c69.rlib" "/tmp/cargo-installyqQgJ1/release/deps/librustc_demangle-f4ab8b54ec54ece8.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libitertools-9a1f466c7d95b679.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libeither-3e3b8d0bde29ae6f.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libxcb-d7a47d4a8d9f5baa.rlib" "/tmp/cargo-installyqQgJ1/release/deps/liblibc-84daafcb68f5c7d3.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libi3ipc-dadf7c0a61ba834c.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libserde_json-2cdac68885c45f2c.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libryu-ef2af33493f472be.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libitoa-9362a2041495c501.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libserde-57253e2c3da4cef7.rlib" "/tmp/cargo-installyqQgJ1/release/deps/liblog-310f65f1f10f3ea2.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libcfg_if-6443c9fece9c5a8b.rlib" "/tmp/cargo-installyqQgJ1/release/deps/libbyteorder-c97e92207226d6ea.rlib" "-Wl,--start-group" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6f77337c1826707d.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-e238540f8faf9927.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-78f8506dd5004913.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-c0e64497deb085aa.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-217a514dc8d845c6.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-65e4f8df4b8bbd73.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-fec1b74170245419.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-e74f867eb2f15322.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-72a374d36f3d0a31.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-cb9206ed96de54c3.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-33ee81149d314805.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-2e8740599b11634b.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-241cf59851357bea.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-edc29aa8c04b480f.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-6a141406945fda5a.rlib" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-2408224b4af46d83.rlib" "-Wl,--end-group" "/home/dapper_core/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-d36087076e1dd756.rlib" "-Wl,-Bdynamic" "-lxcb" "-lxcb" "-lxcb" "-lxcb" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
>   = note: /usr/bin/ld: cannot find -lxcb
>           /usr/bin/ld: cannot find -lxcb
>           /usr/bin/ld: cannot find -lxcb
>           /usr/bin/ld: cannot find -lxcb
>           collect2: error: ld returned 1 exit status
> 
> 
> error: aborting due to previous error
> 
> error: failed to compile `i3wsr v1.3.1`, intermediate artifacts can be found at `/tmp/cargo-installyqQgJ1`
> 
> Caused by:
>   could not compile `i3wsr`

**Comment by roosta** [comment]
Hi, that's unfortunate. It's unclear to me why it would fail but if I was to hazard a guess I'd say you're missing some dependency on your system. What distro are you running? What version of rust are you using? Are you using [rustup](https://rustup.rs/) to install the rust compiler, and if so are you using stable or nightly?

**Comment by ghost** [comment]
I'm using i3 installed on popOS, and I ran "curl https://sh.rustup.rs -sSf | sh" to install what I assumed to be both cargo and rustup.

**Comment by roosta** [comment]
I was able to reproduce and fix on a clean ubuntu VM by installing:
```bash
sudo apt-get install libxcb1-dev
```
I'll add a note to readme if this works for you

**Comment by ghost** [comment]
Seems to have worked like a charm! Thank you!
