### ISSUE TITLE
option for hiding windows names

### ISSUE THREAD

**Issue by adaigre** [roosta/i3wsr#19]
Hi!

I was looking for almost exactly what you're program is doing so thanks for your work!
The only thing is I just want to show icons for a few apps but only want workspace number when there is no match. Currently there is the name of the applications written in letter, but it can take a lot of space.

Thanks!

**Comment by roosta** [comment]
Hello!
Thanks for opening an issue and using i3wsr :) I thought the `no-names` option would take care of that but seems it doesn't work like you describe. I'll try to include a fix for this in the next update, stay tuned.

**Comment by roosta** [comment]
The branch [1.4.0](https://github.com/roosta/i3wsr/tree/1.4.0) contains a fix for your issue. When using option `no_names` will remove all names, while retaining icons. Previous behavior for `no_names` is now `no_icon_names`. Could you try out the branch and see if it works for you?

A full release will take a little while longer, I got some other changes upcoming, so you'll have to use the 1.4.0 branch for the time being.

**Comment by adaigre** [comment]
I've just tried the 1.4.0 branch and it seems to work exactly like I wanted!

Unrelated but if I understood correctly, there is no way to match a window by its name (WM_NAME)?

**Comment by roosta** [comment]
Great!

> Unrelated but if I understood correctly, there is no way to match a window by its name (WM_NAME)?

No, I don't remember exactly why I chose to disregard WM_NAME, but it might have been that they were usually to verbose or something like that. Is it a feature you'd like to see?

**Comment by adaigre** [comment]
It would be great because I'd like to put a specific icon when mutt is running in Alacritty but WM_CLASS is always "Alacritty".
WM_NAME has "mutt /folder/where/it/was/launched" in this case. So I think #16 would be required too (to strip what is after "mutt")? Unfortunately I don't have the skills to contribute...

For the time being the 1.4.0 branch provides enough for me so again thanks for your work!
I'm closing this issue since it is solved.

**Comment by gschievelbein** [comment]
> It would be great because I'd like to put a specific icon when mutt is running in Alacritty but WM_CLASS is always "Alacritty".
> WM_NAME has "mutt /folder/where/it/was/launched" in this case. So I think #16 would be required too (to strip what is after "mutt")? Unfortunately I don't have the skills to contribute...
> 
> For the time being the 1.4.0 branch provides enough for me so again thanks for your work!
> I'm closing this issue since it is solved.

I also agree that some way of using the wm_name would be great, specially for applications running on a terminal. Right now I display custom icons for my e-mail client and music player because I open them automatically on start-up on a scratchpad with a custom wm_class name, but it would be nice to also have icons for newly opened applications without having to deal with changing wm_class everytime.

**Comment by roosta** [comment]
I'll try to include it in 1.4.0 along with regex alias matching. Thank you both for the feedback.

**Comment by roosta** [comment]
Try out the new [regex](https://github.com/roosta/i3wsr/tree/regex) branch to try out the new regex alias matching. The syntax is:
```toml
"Gimp-\\d\\.\\d\\d" = "Gimp"
```
Where the double backslashes are needed to get a literal backslash in the expression.

Further conversation about this will take place in #16

**Comment by adaigre** [comment]
I just tried but unfortunately it doesn't fit my case: matching "^mutt" in WM_NAME.
