### ISSUE TITLE
wm_property to "name" produce get_title error 

### ISSUE THREAD

**Issue by adaigre** [roosta/i3wsr#21]
Hello,

I'm testing the 2.0 version but can't get `wm_property = "name"` to work.
I have the following messages:
`get_title error: invalid utf-8 sequence of 1 bytes from index 9
`

Thanks for your work!

**Comment by roosta** [comment]
Hi
That's unfortunate, you wouldn't happen to remember which applications you were running at the time that could possibly produce that error?

**Comment by adaigre** [comment]
It seems to happen when applications has accented characters in their names (like "Actualités").

**Comment by roosta** [comment]
thanks, that narrows it down. I'll get to work fixing it as soon as I'm able, thanks for reporting.

**Comment by roosta** [comment]
I think I fixed the issue in [fix21](https://github.com/roosta/i3wsr/tree/fix21), mind giving it a go?

**Comment by adaigre** [comment]
It seems to solve this issue!

However the issue I have now is that windows name changes are not detected (I have to switch between workspace). Do you want me to open a other issue?

**Comment by roosta** [comment]
Great!
>However the issue I have now is that windows name changes are not detected (I have to switch between workspace). Do you want me to open a other issue?

Strictly speaking its not anything I can do about that in i3wsr, terminal apps will not produce any window events. I'll try to tinker with a launch script, see if I can figure something out. No need to open an issue I think.

**Comment by adaigre** [comment]
This means that terminal apps don't trigger the "title" window event of I3 IPC? [https://i3wm.org/docs/ipc.html#_window_event](https://i3wm.org/docs/ipc.html#_window_event)

I'm closing this issue since it is resolved! Again, thanks for you work!

**Comment by roosta** [comment]
Yeah that's right, no event to listen to for terminal applications. What I was thinking was to write a script that wraps whatever your launching with a IPC tigger event or something similar. A slight hassle but I cant think of any other way.
