### ISSUE TITLE
Duplicate workspace is created when applications are assigned workspaces

### ISSUE THREAD

**Issue by pnchinmay** [roosta/i3wsr#22]
Hi
Thanks for such a wonderful tool. It has been working great.  

However, there's one problem. 
I have assigned workspaces to classes as ```assign [class=Google-chrome] 2```.  
Whenever I open a new window of chrome, it opens directly in the 2nd workspace. This is what i3 does.  

But, when I'm running i3wsr, it creates another new workspace numbered 2 and open the new window in that workspace. This works fine when there are no applications open in 2nd workspace. Other times, it just gets confusing and the binding for going to workspace number 2 only goes to the newly formed 2nd workspace and not the previously opened 2nd workspace.

I've already changed the bindings from ```bindsym $mod+2 workspace 2``` to ```bindsym $mod+2 workspace number 2```.
I also tried doing something like ```for_window [class="Spotify"] move container to workspace 3, workspace number 3```. But, it didn't work and this one also created another new workspace numbered 3.

Is there any workaround ? Kindly suggest
Thanks

**Comment by roosta** [comment]
Hi
Thanks a lot, glad you like it. I am aware of said problem, I just haven't looked into it that hard because I assumed it was an i3 config issue. But I'll look into it a bit more and let you know what I find.

**Comment by pnchinmay** [comment]
Oh thanks a lot for such a quick reply. 
I'll wait :D

**Comment by roosta** [comment]
I was able to get this to work using workspace variables. I got my workspaces defined like this:
```i3
set $pws_e "3:[E]"
bindsym $mod+e workspace number $pws_e
```
Then instead of assigning to a number, I assign to workspace string like detailed [here](https://i3wm.org/docs/userguide.html#assign_workspace)

>  You can also specify a number + name. If the workspace with number 2 exists,  assign will skip the text part.
> assign [class="^URxvt$"] → number "2: work"

```i3
assign [class="(?i)firefox$$"] number $pws_e
```
I hope this helps!

**Comment by pnchinmay** [comment]
Oh great
It works like a charm
I modified for all workspaces and assigned classes :D
Thanks a lot
