### ISSUE TITLE
i3wsr incompatible with auto-assigning applications to workspaces

### ISSUE THREAD

**Issue by 12ak** [roosta/i3wsr#23]
When I am running i3wsr and I have assigned certain classes in my i3 config to start on specific workspaces (e.g. "assign [class="Kodi"] $ws10"), if I have another class auto assigned to the same workspace, two workspaces of the same number are created. This behaviour doesn't occur when i3wsr is disabled. Instead what I would expect to happen - both classes start on the same workspace - occurs.

**Comment by roosta** [comment]
What does the variable `$ws10` contain?

**Comment by 12ak** [comment]
Just the number 10

**Comment by roosta** [comment]
You need the assignment look like this then `assign [class="Kodi"] number $ws10`, make note of `number` before the variable.

**Comment by 12ak** [comment]
Thank you that solved it
