### ISSUE TITLE
make WM_CLASS overridable

### ISSUE THREAD

**Issue by steinex** [roosta/i3wsr#3]
Hi,

thanks for this tool!

It would be nice to be able to override WM_CLASS so that i3wsr would show them with a different name in i3. Maybe via a configuration file or CLI option?

That way it would be possible to have `Xfce4-terminal` shown as `term` for example.

**Comment by roosta** [comment]
Hi, thanks for using i3wsr and posting an issue! It's a good idea, maybe a config file would be best suited for this. I'll see about adding this as soon as I'm able.

**Comment by roosta** [comment]
Sorry about the delay on this, been swamped with other projects and work, and my rust has gotten rusty. Any help on this would be greatly appreciated.

**Comment by roosta** [comment]
https://github.com/roosta/i3wsr/releases/tag/v1.2.0
