### ISSUE TITLE
[HELP] Empty workspace custom label

### ISSUE THREAD

**Issue by diffficult** [roosta/i3wsr#35]
Was looking for an option or setting in the config.toml that let's me set the default label for a workspace even when there's nothing there at all. The same way you can set an icon or text label for a program running in a workspace, can you set a default label to be displayed when you move to a workspace that has no windows at all? Right now I can only see the number that belongs to that  can.

For example i want to have a Browser running on workspace 1, and see it's icon displayed like "🌐" and if I move to the next empty one, instead of seeing a "2" another icon I choose like "🆓"

**Comment by roosta** [comment]
I can set that up this weekend. It'll have to live in the dev branch for a little while until everything is squared.

**Comment by diffficult** [comment]
That would be great. Thought there was already something like that working but I was missing something in my config file.

My base i3 config had something like this

```
# Set workspaces -----------------------------------------
set $workspace1 "1: "
set $workspace2 "2: "
set $workspace3 "3: "
set $workspace4 "4: "
set $workspace5 "5: "
set $workspace6 "6: "
set $workspace7 "7: "
set $workspace8 "8: "
set $workspace9 "9: "
set $workspace10 "10: "
```

with fontawesome symbols for each space like almost every other i3 user. Would be nice to keep the placeholder label/symbol if there's no window in that workspace.

**Comment by roosta** [comment]
I've added the option

**Comment by roosta** [comment]
I've added the option `empty_label`, that goes below `[general]` in config. Hope this works for you, a bit later than promised, but I was unable to get to it until now.

**Comment by diffficult** [comment]
no problem. Thanks for the work, will test it out this weekend.
