### ISSUE TITLE
i3wsr not capturing WM_NAME for chrome tabs

### ISSUE THREAD

**Issue by TonyStew** [roosta/i3wsr#36]
I'm trying to add specific icons based on the contents of a chrome tab (for example YouTube).  I can get this from the name as seen by:  
```
$ xprop WM_NAME
WM_NAME(UTF8_STRING) = "YouTube - Google Chrome"
```
However, I am unable to alias this in i3wsr.  I've tried various versions of `"^YouTube - Google Chrome$"`, `"YouTube"`, and `".*YouTube.*"`.  None of these successfully change the i3 window name.

Additionally, the window name is always `"Google-chrome"` (the WM_CLASS) regardless of the WM_NAME property, despite me having `wm_property = "name"` set and seeing other i3 windows change name by the content's WM_NAME (I made sure to trigger i3 events while YouTube was the visible tab and was included in the WM_NAME as part of this testing).

I'm wondering why the behavior for chrome is different from other applications.  My best guess is it has to do with either the "-" in the WM_NAME or the fact that the WM_NAME attribute is a UTF8_STRING for chrome rather than a STRING (as it seems to be in most applications).

Please let me know if additional info would be helpful in reproducing this or if I'm misunderstanding the expected behavior.

**Comment by roosta** [comment]
Hi @TonyStew, thanks for reporting. Would you mind trying the develop branch and see if the issue is the same? The syntax has changed a bit, so make sure to check the readme of that branch. But in short the `wm_property` is no longer used, instead matching on property like this:

```toml
[aliases.class]
"^firefoxdeveloperedition$" = "Firefox-dev"

[aliases.instance]
"open.spotify.com" = "Spotify"
```

**Comment by TonyStew** [comment]
That worked!  Thanks.
