### ISSUE TITLE
Configurable separator

### ISSUE THREAD

**Issue by PrimaMateria** [roosta/i3wsr#5]
Option in the config file to set string used as separator between window names.

**Comment by roosta** [comment]
Done, check out [release v1.2.1](https://github.com/roosta/i3wsr/releases/tag/v1.2.1)

**Comment by steinex** [comment]
I almost feel bad about it, but I have one really minor nitpick about this one:

With `separator = ""`, there is a space/gap between icons. This is especially visible when run with `--no-names`. I think this is the last thing that is holding me back from using i3wsr full time. :D

**Comment by roosta** [comment]
I have some issues removing space ATM, not sure why. Looking into it but a fix might not be incoming until next week some time. Could you illustrate what you are trying to do?

**Comment by steinex** [comment]
Sure. Right now, my workspaces look like this:
![without_spaces](https://user-images.githubusercontent.com/201358/71726121-6a044d80-2e36-11ea-91d9-a8cf6e6e8980.png)

With i3wsr, `--no-names` and `separator = ""`, it looks like this:
![i3wsr](https://user-images.githubusercontent.com/201358/71726176-94eea180-2e36-11ea-9a5b-7436d3c8fd3a.png)

As you can see there is an extra space character between icons and a trailing space after the last icon of a workspace. I'd prefer if they would be absent - if one wants them, they could just use the new separator option for that too I guess.

Thank you very much!

**Comment by roosta** [comment]
So you'd like all whitespace removed between icons? I can remove the trailing whitespace no problem but I need some way of separating icons from the lead information in the workspace (workspace number etc) So if I remove spaces between icons i3wsr doesn't know when lead information ends and workspace names start, at least not with the current implementation

**Comment by roosta** [comment]
Oh, there is an extra whitespace char between them? Sorry, misunderstood there for a sec, I'll try to fix that. Thanks for your feedback :)

**Comment by roosta** [comment]
OK, I believe i fixed the issue in the [whitespace](https://github.com/roosta/i3wsr/tree/whitespace) branch. Could you pop over to that branch and test it and see if it works for you @steinex?

**Comment by steinex** [comment]
Can confirm it works! :)

I noticed that it will remove any whitespace between the icons now though, not just the extra one (at least it looks that way). However, when using `separator = " "` (mind the space) it's perfectly fine for me now and looks like on the first screenshot I posted above.

Just something to keep in mind, most people want to use something like `separator = " | "` now I guess so it doesn't look weird - or you bring just that one space back minus the extraneous one. :-)

**Comment by roosta** [comment]
The names should now only be separated by `separator` via `some-vector.join()` so there isn't any trailing whitespace that I can do anything about (you sure its not the your bar config?) The separator defaults to `" | "` unless something else is in the config so I think this should work for most users

**Comment by steinex** [comment]
Are you sure it defaults to `" | "`? When I set that explicitely it looks normal, if I uncomment that out or change it to `"|"` there is no single whitespace left, making it look squeezed.

It seems that with this branch, actually 2 spaces between the icons got removed instead of one. I can live fine with that using `" "`, I just want you to know so it doesn't change beharviour on users.

**Comment by steinex** [comment]
Oh, I missed your second commit in that branch that actually switches the default to `" | "` (8edb11a1aea82b8a06ddcc0a624f3ae9ce7d4bfa).

Just tested with this and everything looks good now!

Thanks for your patience and your work on this! :-)

**Comment by roosta** [comment]
Thank you for helpful feedback, I'll release a new version now

**Comment by roosta** [comment]
https://github.com/roosta/i3wsr/releases/tag/v1.2.2
