### ISSUE TITLE
Crashing when WM_CLASS is not set

### ISSUE THREAD

**Issue by 3e849f2e5c** [roosta/i3wsr#8]
Some edge-case programs do not set a WM_CLASS for their window and cause i3wsr to crash while one is present, such cases include the Linux version of the game [Plague Inc: Evolved](https://store.steampowered.com/app/246620/Plague_Inc_Evolved/) and the Android emulator provided by [Android Studio](https://developer.android.com/studio/).

If i3wsr was launched before the said window appears i3wsr will cease to function until the said window has been closed and will resume normal function afterwards. If trying to launch i3wsr while the said window is active it will simply exit instantly.

![](https://kosblue.com/e/pdhfsh.png)

**Comment by roosta** [comment]
Thank you for the report, I'll see about fixing this as soon as I'm able.

**Comment by roosta** [comment]
@3e849f2e5c can you try out [hotfix-8](https://github.com/roosta/i3wsr/tree/hotfix-8)? lemme know if that works for you.

**Comment by 3e849f2e5c** [comment]
Tested the branch and the program now works properly while the Android emulator window is active, skipping it from displaying on the workspace label
![](https://kosblue.com/e/pigfjn.png)

**Comment by roosta** [comment]
new release on https://crates.io/crates/i3wsr
v1.2.3 with this fix
